[workspace]

members = [
    "autoschematic",
    "autoschematic-server",
    "autoschematic-core",
    "autoschematic-lsp",
    "autoschematic-macros",
    #"connectors/autoschematic-connector-python-host",
]

[profile.release]
debug = 1
