[package]
name = "autoschematic-macros"
description = "Proc macro functionality for Autoschematic"
license = "AGPL-3.0"
version = "0.10.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.41"
syn = "2.0.108"
